#!/usr/bin/env bash
# This script shows Best School 10 times, but for the 9th
#+ iteration, displays Best School and then Hi on a new line


n=1

while ((i<=10)); do
        if ((i==9))
        then
                echo "Hi"
        fi
        echo "Best School"
        ((n++))

done