#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash

filelist=$(ls)

for item in $filelist; do
  echo "$item" | cut -d '-' -f2
done